### ISSUE TITLE
with_indifferent_access

### ISSUE THREAD

**Issue by Vlagilen** [yuri-zubov/payonline#10]
Rails 5.
Every time when i get callback (Payonline::PaymentResponse.new(params)), it's error: 

> NoMethodError (undefined method `with_indifferent_access' for #<ActionController::Parameters

If i edit it to `params.to_unsafe_h`, then no error, is it correct?

**Comment by yuri-zubov** [comment]
@Vlagilen this gem was written for rails 4.2.
if I understand you correctly you need to permit params
```
response = Payonline::PaymentResponse.new(params.permit!)
```
or
```
response = Payonline::PaymentResponse.new(params.permit!.to_h)
```
more information you can find this - http://edgeguides.rubyonrails.org/action_controller_overview.html#strong-parameters

**Comment by Vlagilen** [comment]
@yuri-zubov 

> response = Payonline::PaymentResponse.new(params.permit!.to_h)

It's helps. Thx
